import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({                         //Esto es una Fuente de Texto para este Layout
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({                         //Esto es una Fuente de Texto para este Layout
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/*
  Metadata minima para una pagina(se puede exportar a otras paginas de la app).
  Si una pagina en cuestion no tiene metadata, Next agarrará la metadata por defecto del layout principal o del subsiguiente.
*/
export const metadata: Metadata = {                   
  title: "Carlos Next App",
  description: "Generated by Megas",
};


//Este es nuestro Layout principal o RootLayout, todo lo quee se haya en este layout va a impactar en todas las paginas de la app.
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
